export const PLATFORM_UI_SCRIPT = [
  "const boot = window.__PROJECT_MANAGER_PLATFORM__ ?? { pathname: '/' };",
  "const state = {",
  "  pathname: boot.pathname,",
  "  token: '',",
  "  projects: [],",
  "  selectedProject: null,",
  "  projectTree: null,",
  "  selectedFilePath: '',",
  "  fileContent: null,",
  "  fileDraft: '',",
  "  tasks: [],",
  "  selectedTask: null,",
  "  summary: null,",
  "  busy: false,",
  "  message: 'Control plane ready.'",
  "};",
  "const els = {",
  "  route: document.querySelector('[data-route]'),",
  "  token: document.querySelector('[data-admin-token]'),",
  "  form: document.querySelector('[data-ai-form]'),",
  "  project: document.querySelector('[data-project-slug]'),",
  "  task: document.querySelector('[data-task-slug]'),",
  "  prompt: document.querySelector('[data-prompt]'),",
  "  projects: document.querySelector('[data-project-list]'),",
  "  projectDetail: document.querySelector('[data-project-detail]'),",
  "  fileTree: document.querySelector('[data-file-tree]'),",
  "  filePreview: document.querySelector('[data-file-preview]'),",
  "  tasks: document.querySelector('[data-task-list]'),",
  "  summary: document.querySelector('[data-task-summary]'),",
  "  status: document.querySelector('[data-status]'),",
  "  apply: document.querySelector('[data-apply-task]')",
  "};",
  "function renderStatus() {",
  "  if (els.status) els.status.textContent = state.message;",
  "  if (els.route) els.route.textContent = state.pathname;",
  "  if (els.apply) els.apply.disabled = state.selectedTask === null || state.selectedTask.status !== 'completed' || state.busy;",
  "}",
  "function currentFileIsDirty() {",
  "  return state.selectedFilePath.length > 0 && state.fileContent !== null && state.fileDraft !== state.fileContent;",
  "}",
  "function renderProjectDetail() {",
  "  if (!els.projectDetail) return;",
  "  if (!state.selectedProject) {",
  "    els.projectDetail.innerHTML = '<p>No project selected.</p>';",
  "    return;",
  "  }",
  "  const runtimeHref = state.selectedProject.runtime === 'static' ? `/p/${state.selectedProject.slug}` : `/app/${state.selectedProject.slug}`;",
  "  const description = state.selectedProject.description ?? 'No project description yet.';",
  "  els.projectDetail.innerHTML = `<h3>${state.selectedProject.name}</h3><p>${description}</p><div class=\"meta-grid\"><span><strong>Runtime</strong>${state.selectedProject.runtime}</span><span><strong>Route</strong>${state.selectedProject.route}</span><span><strong>Entry</strong>${state.selectedProject.entry}</span><span><strong>Framework</strong>${state.selectedProject.framework ?? 'n/a'}</span></div><p><a class=\"project-runtime\" href=\"${runtimeHref}\">Open runtime view</a></p>`;",
  "}",
  "function renderProjects() {",
  "  if (!els.projects) return;",
  "  els.projects.innerHTML = state.projects.map((project) => `<li><a href=\"/projects/${project.slug}\" class=\"project-link${state.selectedProject && state.selectedProject.slug === project.slug ? ' is-active' : ''}\" data-project-slug-link=\"${project.slug}\"><strong>${project.slug}</strong><span>${project.runtime}</span></a></li>`).join('');",
  "  els.projects.querySelectorAll('[data-project-slug-link]').forEach((link) => {",
  "    link.addEventListener('click', async (event) => {",
  "      event.preventDefault();",
  "      const slug = link.getAttribute('data-project-slug-link') ?? '';",
  "      if (!slug) return;",
  "      history.pushState({}, '', `/projects/${slug}`);",
  "      state.pathname = `/projects/${slug}`;",
  "      await selectProject(slug);",
  "      renderStatus();",
  "    });",
  "  });",
  "}",
  "function renderTasks() {",
  "  if (!els.tasks) return;",
  "  els.tasks.innerHTML = state.tasks.map((task) => `<li><button type=\"button\" data-task-id=\"${task.taskId}\" class=\"task-row${state.selectedTask && state.selectedTask.taskId === task.taskId ? ' is-active' : ''}\"><strong>${task.projectSlug}/${task.taskSlug}</strong><span>${task.status}</span></button></li>`).join('');",
  "  els.tasks.querySelectorAll('[data-task-id]').forEach((button) => {",
  "    button.addEventListener('click', () => selectTask(button.getAttribute('data-task-id') ?? ''));",
  "  });",
  "}",
  "function renderSummary() {",
  "  if (!els.summary) return;",
  "  if (!state.selectedTask) {",
  "    els.summary.innerHTML = '<p>No AI task selected.</p>';",
  "    return;",
  "  }",
  "  const changes = state.summary ? state.summary.changes.map((change) => `<li><code>${change.kind}</code> ${change.path}</li>`).join('') : '<li>No summary artifact yet.</li>';",
  "  const error = state.selectedTask.error ? `<p class=\"error\">${state.selectedTask.error}</p>` : '';",
  "  const applied = state.selectedTask.appliedAt ? `<p>Applied at ${state.selectedTask.appliedAt}</p>` : '<p>Workspace not applied yet.</p>';",
  "  els.summary.innerHTML = `<h3>${state.selectedTask.projectSlug}/${state.selectedTask.taskSlug}</h3><p>Status: ${state.selectedTask.status}</p>${applied}${error}<ul>${changes}</ul>`;",
  "}",
  "function escapeHtml(value) {",
  "  return String(value)",
  "    .replaceAll('&', '&amp;')",
  "    .replaceAll('<', '&lt;')",
  "    .replaceAll('>', '&gt;')",
  "    .replaceAll('\"', '&quot;');",
  "}",
  "function firstFilePath(node) {",
  "  if (!node) return '';",
  "  if (node.kind === 'file') return node.path;",
  "  for (const child of node.children ?? []) {",
  "    const path = firstFilePath(child);",
  "    if (path) return path;",
  "  }",
  "  return '';",
  "}",
  "function hasFilePath(node, path) {",
  "  if (!node || !path) return false;",
  "  if (node.kind === 'file') return node.path === path;",
  "  return (node.children ?? []).some((child) => hasFilePath(child, path));",
  "}",
  "function renderTreeNode(node, depth = 0) {",
  "  const padding = 12 + depth * 16;",
  "  if (node.kind === 'directory') {",
  "    const children = (node.children ?? []).map((child) => renderTreeNode(child, depth + 1)).join('');",
  "    const label = node.path ? escapeHtml(node.name) : 'workspace';",
  "    return `<li><div class=\"tree-dir\" style=\"padding-left:${padding}px\">${label}</div>${children ? `<ul>${children}</ul>` : ''}</li>`;",
  "  }",
  "  return `<li><button type=\"button\" class=\"file-link${state.selectedFilePath === node.path ? ' is-active' : ''}\" style=\"padding-left:${padding}px\" data-file-path=\"${escapeHtml(node.path)}\"><span>${escapeHtml(node.name)}</span><small>${node.size}b</small></button></li>`;",
  "}",
  "function bindFileTreeEvents() {",
  "  if (!els.fileTree) return;",
  "  els.fileTree.querySelectorAll('[data-file-path]').forEach((button) => {",
  "    button.addEventListener('click', () => {",
  "      const path = button.getAttribute('data-file-path') ?? '';",
  "      void selectFile(path);",
  "    });",
  "  });",
  "}",
  "function renderFileTree() {",
  "  if (!els.fileTree) return;",
  "  if (!state.selectedProject) {",
  "    els.fileTree.innerHTML = '<p>No project selected.</p>';",
  "    return;",
  "  }",
  "  if (!state.projectTree) {",
  "    els.fileTree.innerHTML = '<p>Loading workspace…</p>';",
  "    return;",
  "  }",
  "  const children = (state.projectTree.children ?? []).map((child) => renderTreeNode(child, 0)).join('');",
  "  els.fileTree.innerHTML = children ? `<ul>${children}</ul>` : '<p>Project workspace is empty.</p>';",
  "  bindFileTreeEvents();",
  "}",
  "function renderFilePreview() {",
  "  if (!els.filePreview) return;",
  "  if (!state.selectedProject) {",
  "    els.filePreview.innerHTML = '<p>No project selected.</p>';",
  "    return;",
  "  }",
  "  if (!state.selectedFilePath) {",
  "    els.filePreview.innerHTML = '<p>Select a file to inspect its current project content.</p>';",
  "    return;",
  "  }",
  "  if (state.fileContent === null) {",
  "    els.filePreview.innerHTML = '<p>Loading file…</p>';",
  "    return;",
  "  }",
  "  const saveDisabled = state.busy || !currentFileIsDirty() ? ' disabled' : '';",
  "  const saveLabel = state.busy ? 'Saving...' : 'Save File';",
  "  const dirtyState = currentFileIsDirty() ? 'Unsaved changes' : 'Saved';",
  "  els.filePreview.innerHTML = `<div class=\"file-preview-head\"><strong>${escapeHtml(state.selectedFilePath)}</strong><span>${escapeHtml(state.selectedProject.slug)} · ${dirtyState}</span></div><div class=\"file-editor\"><textarea data-file-editor spellcheck=\"false\">${escapeHtml(state.fileDraft)}</textarea><div class=\"file-actions\"><button type=\"button\" data-save-file${saveDisabled}>${saveLabel}</button></div></div>`;",
  "  const editor = els.filePreview.querySelector('[data-file-editor]');",
  "  if (editor) {",
  "    editor.addEventListener('input', () => {",
  "      state.fileDraft = editor.value;",
  "      renderFilePreview();",
  "    });",
  "  }",
  "  const saveButton = els.filePreview.querySelector('[data-save-file]');",
  "  if (saveButton) {",
  "    saveButton.addEventListener('click', () => {",
  "      void handleSaveFile();",
  "    });",
  "  }",
  "}",
  "async function requestJson(path, init = {}) {",
  "  const response = await fetch(path, init);",
  "  const body = await response.json();",
  "  if (!response.ok) throw new Error(body.error ?? `request failed (${response.status})`);",
  "  return body;",
  "}",
  "function authHeaders() {",
  "  const headers = { 'content-type': 'application/json' };",
  "  if (state.token) headers.authorization = `Bearer ${state.token}`;",
  "  return headers;",
  "}",
  "function initialProjectSlug() {",
  "  const match = state.pathname.match(/^\\/projects\\/([a-z0-9-]+)/);",
  "  return match ? (match[1] ?? '') : '';",
  "}",
  "async function refreshProjects() {",
  "  const payload = await requestJson('/api/projects');",
  "  state.projects = payload.projects;",
  "  const projectSlug = initialProjectSlug() || state.selectedProject?.slug || state.projects[0]?.slug || '';",
  "  if (projectSlug) await selectProject(projectSlug);",
  "  renderProjects();",
  "}",
  "async function refreshProjectWorkspace() {",
  "  if (!state.selectedProject) return;",
  "  state.projectTree = null;",
  "  state.fileContent = null;",
  "  state.fileDraft = '';",
  "  renderFileTree();",
  "  renderFilePreview();",
  "  const payload = await requestJson(`/api/projects/${state.selectedProject.slug}/file-tree`);",
  "  state.projectTree = payload.tree;",
  "  renderFileTree();",
  "  const nextFilePath = hasFilePath(payload.tree, state.selectedFilePath) ? state.selectedFilePath : firstFilePath(payload.tree);",
  "  if (nextFilePath) {",
  "    await selectFile(nextFilePath);",
  "    return;",
  "  }",
  "  state.selectedFilePath = '';",
  "  state.fileContent = '';",
  "  state.fileDraft = '';",
  "  renderFilePreview();",
  "}",
  "async function selectProject(projectSlug) {",
  "  if (!projectSlug) return;",
  "  const project = await requestJson(`/api/projects/${projectSlug}`);",
  "  state.selectedProject = project;",
  "  state.selectedFilePath = '';",
  "  state.fileContent = null;",
  "  state.fileDraft = '';",
  "  if (els.project) els.project.value = project.slug;",
  "  renderProjects();",
  "  renderProjectDetail();",
  "  await refreshProjectWorkspace();",
  "}",
  "async function selectFile(path) {",
  "  if (!state.selectedProject || !path) return;",
  "  state.selectedFilePath = path;",
  "  state.fileContent = null;",
  "  state.fileDraft = '';",
  "  renderFileTree();",
  "  renderFilePreview();",
  "  const payload = await requestJson(`/api/projects/${state.selectedProject.slug}/file?path=${encodeURIComponent(path)}`);",
  "  state.fileContent = payload.content;",
  "  state.fileDraft = payload.content;",
  "  renderFilePreview();",
  "}",
  "async function handleSaveFile() {",
  "  if (!state.selectedProject || !state.selectedFilePath || !currentFileIsDirty()) return;",
  "  state.busy = true;",
  "  state.message = `Saving ${state.selectedFilePath}...`;",
  "  renderStatus();",
  "  renderFilePreview();",
  "  try {",
  "    await requestJson(`/api/projects/${state.selectedProject.slug}/file`, {",
  "      method: 'PUT',",
  "      headers: authHeaders(),",
  "      body: JSON.stringify({",
  "        path: state.selectedFilePath,",
  "        content: state.fileDraft",
  "      })",
  "    });",
  "    state.fileContent = state.fileDraft;",
  "    state.message = `Saved ${state.selectedFilePath}.`;",
  "    await refreshProjectWorkspace();",
  "  } catch (error) {",
  "    state.message = error instanceof Error ? error.message : 'unknown project file error';",
  "  } finally {",
  "    state.busy = false;",
  "    renderStatus();",
  "    renderFilePreview();",
  "  }",
  "}",
  "async function refreshTasks() {",
  "  const payload = await requestJson('/api/ai/tasks');",
  "  state.tasks = payload.tasks;",
  "  renderTasks();",
  "  if (!state.selectedTask && state.tasks.length > 0) await selectTask(state.tasks[0].taskId);",
  "}",
  "async function selectTask(taskId) {",
  "  if (!taskId) return;",
  "  const payload = await requestJson(`/api/ai/tasks/${taskId}`);",
  "  state.selectedTask = payload.task;",
  "  state.summary = payload.task.summaryPath ? (await requestJson(`/api/ai/tasks/${taskId}/summary`)).summary : null;",
  "  renderTasks();",
  "  renderSummary();",
  "  renderStatus();",
  "}",
  "async function waitForTask(taskId) {",
  "  for (let attempt = 0; attempt < 120; attempt += 1) {",
  "    const payload = await requestJson(`/api/ai/tasks/${taskId}`);",
  "    if (payload.task.status === 'completed' || payload.task.status === 'failed') return payload.task;",
  "    await new Promise((resolve) => setTimeout(resolve, 1000));",
  "  }",
  "  throw new Error(`ai task did not settle: ${taskId}`);",
  "}",
  "async function handleCreate(event) {",
  "  event.preventDefault();",
  "  state.busy = true;",
  "  state.message = 'AI task enqueued.';",
  "  renderStatus();",
  "  try {",
  "    const payload = await requestJson('/api/ai/tasks', {",
  "      method: 'POST',",
  "      headers: authHeaders(),",
  "      body: JSON.stringify({",
  "        projectSlug: els.project?.value ?? '',",
  "        taskSlug: els.task?.value ?? '',",
  "        prompt: els.prompt?.value ?? ''",
  "      })",
  "    });",
  "    state.message = 'AI task running.';",
  "    renderStatus();",
  "    const task = await waitForTask(payload.task.taskId);",
  "    state.message = task.status === 'completed' ? 'AI task completed.' : 'AI task failed.';",
  "    await refreshTasks();",
  "    await selectTask(task.taskId);",
  "  } catch (error) {",
  "    state.message = error instanceof Error ? error.message : 'unknown ai task error';",
  "    renderStatus();",
  "  } finally {",
  "    state.busy = false;",
  "    renderStatus();",
  "  }",
  "}",
  "async function handleApply() {",
  "  if (!state.selectedTask) return;",
  "  state.busy = true;",
  "  state.message = 'Applying workspace back to the project.';",
  "  renderStatus();",
  "  try {",
  "    const payload = await requestJson(`/api/ai/tasks/${state.selectedTask.taskId}/apply`, {",
  "      method: 'POST',",
  "      headers: authHeaders()",
  "    });",
  "    state.selectedTask = payload.task;",
  "    state.message = `Applied ${payload.result.changedFiles} changed files.`;",
  "    await refreshTasks();",
  "    if (state.selectedProject && state.selectedTask.projectSlug === state.selectedProject.slug) {",
  "      await refreshProjectWorkspace();",
  "    }",
  "    renderSummary();",
  "  } catch (error) {",
  "    state.message = error instanceof Error ? error.message : 'unknown ai task error';",
  "  } finally {",
  "    state.busy = false;",
  "    renderStatus();",
  "  }",
  "}",
  "async function start() {",
  "  if (els.token) els.token.addEventListener('input', () => { state.token = els.token.value.trim(); });",
  "  if (els.form) els.form.addEventListener('submit', handleCreate);",
  "  if (els.apply) els.apply.addEventListener('click', handleApply);",
  "  window.addEventListener('popstate', async () => {",
  "    state.pathname = window.location.pathname;",
  "    await refreshProjects();",
  "    renderStatus();",
  "  });",
  "  renderStatus();",
  "  await refreshProjects();",
  "  await refreshTasks();",
  "  setInterval(() => { void refreshTasks(); }, 5000);",
  "}",
  "void start();"
].join("\n");
