export const PLATFORM_UI_ROUTE_SCRIPT = [
  "function activeSection() {",
  "  const match = state.pathname.match(/^\\/projects\\/[a-z0-9-]+(?:\\/(workspace|versions|ai))?$/);",
  "  return match?.[1] ?? 'overview';",
  "}",
  "function aiComposerElements() {",
  "  return {",
  "    toggle: document.querySelector('[data-ai-compose-toggle]'),",
  "    body: document.querySelector('[data-ai-compose-body]')",
  "  };",
  "}",
  "function workspaceElements() {",
  "  return {",
  "    toggle: document.querySelector('[data-workspace-nav-toggle]'),",
  "    nav: document.querySelector('[data-workspace-nav]'),",
  "    grid: document.querySelector('[data-workspace-grid]'),",
  "    copy: document.querySelector('[data-workspace-copy]')",
  "  };",
  "}",
  "function versionComposerElements() {",
  "  return {",
  "    toggle: document.querySelector('[data-version-compose-toggle]'),",
  "    body: document.querySelector('[data-version-compose-body]')",
  "  };",
  "}",
  "function renderAiComposer() {",
  "  const { toggle, body } = aiComposerElements();",
  "  if (!toggle || !body) return;",
  "  const openState = toggle.getAttribute('data-ai-open');",
  "  const isOpen = openState === null ? state.tasks.length === 0 : openState === 'true';",
  "  toggle.setAttribute('data-ai-open', isOpen ? 'true' : 'false');",
  "  toggle.textContent = isOpen ? 'Hide Composer' : 'New Task';",
  "  body.hidden = !isOpen;",
  "}",
  "function bindAiComposer() {",
  "  const { toggle } = aiComposerElements();",
  "  if (!toggle || toggle.getAttribute('data-ai-bound') === 'true') return;",
  "  toggle.setAttribute('data-ai-bound', 'true');",
  "  toggle.addEventListener('click', () => {",
  "    const nextOpen = toggle.getAttribute('data-ai-open') !== 'true';",
  "    toggle.setAttribute('data-ai-open', nextOpen ? 'true' : 'false');",
  "    renderAiComposer();",
  "  });",
  "}",
  "function renderWorkspaceChrome() {",
  "  const { toggle, nav, grid, copy } = workspaceElements();",
  "  if (!toggle || !nav || !grid || !copy) return;",
  "  const openState = toggle.getAttribute('data-workspace-open');",
  "  const isOpen = openState === null ? true : openState === 'true';",
  "  toggle.setAttribute('data-workspace-open', isOpen ? 'true' : 'false');",
  "  toggle.textContent = isOpen ? 'Focus Editor' : 'Show Tree';",
  "  nav.hidden = !isOpen;",
  "  grid.classList.toggle('is-focused', !isOpen);",
  "  if (!state.selectedProject) {",
  "    copy.textContent = 'Focus on one file at a time.';",
  "    return;",
  "  }",
  "  const selectedFile = state.selectedFilePath || 'No file selected';",
  "  const dirty = currentFileIsDirty() ? 'Unsaved changes' : 'Saved';",
  "  copy.textContent = `${selectedFile} · ${dirty}`;",
  "}",
  "function bindWorkspaceChrome() {",
  "  const { toggle } = workspaceElements();",
  "  if (!toggle || toggle.getAttribute('data-workspace-bound') === 'true') return;",
  "  toggle.setAttribute('data-workspace-bound', 'true');",
  "  toggle.addEventListener('click', () => {",
  "    const nextOpen = toggle.getAttribute('data-workspace-open') !== 'true';",
  "    toggle.setAttribute('data-workspace-open', nextOpen ? 'true' : 'false');",
  "    renderWorkspaceChrome();",
  "  });",
  "}",
  "function renderVersionComposer() {",
  "  const { toggle, body } = versionComposerElements();",
  "  if (!toggle || !body) return;",
  "  const openState = toggle.getAttribute('data-version-open');",
  "  const isOpen = openState === null ? state.versions.length === 0 : openState === 'true';",
  "  toggle.setAttribute('data-version-open', isOpen ? 'true' : 'false');",
  "  toggle.textContent = isOpen ? 'Hide Composer' : 'New Snapshot';",
  "  body.hidden = !isOpen;",
  "}",
  "function bindVersionComposer() {",
  "  const { toggle } = versionComposerElements();",
  "  if (!toggle || toggle.getAttribute('data-version-bound') === 'true') return;",
  "  toggle.setAttribute('data-version-bound', 'true');",
  "  toggle.addEventListener('click', () => {",
  "    const nextOpen = toggle.getAttribute('data-version-open') !== 'true';",
  "    toggle.setAttribute('data-version-open', nextOpen ? 'true' : 'false');",
  "    renderVersionComposer();",
  "  });",
  "}",
  "function buildProjectPath(projectSlug, section = activeSection()) {",
  "  if (!projectSlug) return '/projects';",
  "  return section === 'overview' ? `/projects/${projectSlug}` : `/projects/${projectSlug}/${section}`;",
  "}",
  "function bindSectionLinks(root) {",
  "  root.querySelectorAll('[data-section-link]').forEach((link) => {",
  "    link.addEventListener('click', (event) => {",
  "      event.preventDefault();",
  "      const section = link.getAttribute('data-section-link') ?? 'overview';",
  "      const projectSlug = state.selectedProject?.slug ?? initialProjectSlug();",
  "      if (!projectSlug) return;",
  "      state.pathname = buildProjectPath(projectSlug, section);",
  "      history.pushState({}, '', state.pathname);",
  "      renderFocusedView();",
  "      renderStatus();",
  "    });",
  "  });",
  "}",
  "function renderSectionNav() {",
  "  if (!els.sectionNav || !els.sectionCopy) return;",
  "  const copy = {",
  "    overview: 'Keep the landing route focused on project context and the next action only.',",
  "    workspace: 'Use the workspace route for file navigation and editing without review panels competing for attention.',",
  "    versions: 'Use the versions route for snapshot review, diff inspection, and restore actions.',",
  "    ai: 'Use the AI route for prompt creation, task inspection, and explicit apply actions.'",
  "  };",
  "  const section = activeSection();",
  "  const projectSlug = state.selectedProject?.slug ?? initialProjectSlug();",
  "  els.sectionCopy.textContent = copy[section] ?? copy.overview;",
  "  if (!projectSlug) {",
  "    els.sectionNav.innerHTML = '<p class=\"panel-note\">Select a project to open a focused route.</p>';",
  "    return;",
  "  }",
  "  const sections = [",
  "    { key: 'overview', label: 'Overview' },",
  "    { key: 'workspace', label: 'Workspace' },",
  "    { key: 'versions', label: 'Versions' },",
  "    { key: 'ai', label: 'AI Tasks' }",
  "  ];",
  "  els.sectionNav.innerHTML = sections.map((item) => `<a href=\"${buildProjectPath(projectSlug, item.key)}\" class=\"route-link${section === item.key ? ' is-active' : ''}\" data-section-link=\"${item.key}\">${item.label}</a>`).join('');",
  "  bindSectionLinks(els.sectionNav);",
  "}",
  "function renderOverview() {",
  "  if (!els.overview) return;",
  "  if (!state.selectedProject) {",
  "    els.overview.innerHTML = '<p>Select a project to view a quieter overview.</p>';",
  "    return;",
  "  }",
  "  const projectTasks = state.tasks.filter((task) => task.projectSlug === state.selectedProject.slug);",
  "  const latestTask = projectTasks[0] ?? null;",
  "  const latestVersion = state.versions[0] ?? null;",
  "  const selectedFile = state.selectedFilePath || 'No file selected';",
  "  const runtimeHref = state.selectedProject.runtime === 'static' ? `/p/${state.selectedProject.slug}` : `/app/${state.selectedProject.slug}`;",
  "  els.overview.innerHTML = `<div class=\"overview-shell\"><div class=\"overview-main\"><div class=\"panel-head\"><h2>Project Overview</h2><a href=\"${runtimeHref}\" class=\"project-runtime\">Open runtime view</a></div><p class=\"panel-note\">${escapeHtml(state.selectedProject.description ?? 'No project description yet.')}</p><div class=\"overview-actions\"><a href=\"${buildProjectPath(state.selectedProject.slug, 'workspace')}\" class=\"route-link\" data-section-link=\"workspace\">Open Workspace</a><a href=\"${buildProjectPath(state.selectedProject.slug, 'versions')}\" class=\"route-link\" data-section-link=\"versions\">Open Versions</a><a href=\"${buildProjectPath(state.selectedProject.slug, 'ai')}\" class=\"route-link\" data-section-link=\"ai\">Open AI Tasks</a></div></div><aside class=\"overview-side\"><article class=\"overview-stat\"><strong>Active file</strong><span>${escapeHtml(selectedFile)}</span><p>Edit files only from the workspace route.</p></article><article class=\"overview-stat\"><strong>Latest snapshot</strong><span>${state.versions.length} version${state.versions.length === 1 ? '' : 's'}</span><p>${escapeHtml(latestVersion ? latestVersion.message : 'No snapshots yet.')}</p></article><article class=\"overview-stat\"><strong>Latest AI task</strong><span>${projectTasks.length} task${projectTasks.length === 1 ? '' : 's'}</span><p>${escapeHtml(latestTask ? `${latestTask.taskSlug} · ${latestTask.status}` : 'No AI task yet.')}</p></article></aside></div>`;",
  "  bindSectionLinks(els.overview);",
  "}",
  "function renderFocusedView() {",
  "  bindAiComposer();",
  "  bindWorkspaceChrome();",
  "  bindVersionComposer();",
  "  renderAiComposer();",
  "  renderWorkspaceChrome();",
  "  renderVersionComposer();",
  "  renderSectionNav();",
  "  renderOverview();",
  "  const section = activeSection();",
  "  if (els.overview) els.overview.hidden = section !== 'overview';",
  "  if (els.workspacePanel) els.workspacePanel.hidden = section !== 'workspace';",
  "  if (els.versionsPanel) els.versionsPanel.hidden = section !== 'versions';",
  "  if (els.aiPanel) els.aiPanel.hidden = section !== 'ai';",
  "}"
];
