export const PLATFORM_UI_ROUTE_SCRIPT = [
  "function activeSection() {",
  "  const match = state.pathname.match(/^\\/projects\\/[a-z0-9-]+(?:\\/(workspace|versions|ai))?$/);",
  "  return match?.[1] ?? 'overview';",
  "}",
  "function buildProjectPath(projectSlug, section = activeSection()) {",
  "  if (!projectSlug) return '/projects';",
  "  return section === 'overview' ? `/projects/${projectSlug}` : `/projects/${projectSlug}/${section}`;",
  "}",
  "function bindSectionLinks(root) {",
  "  root.querySelectorAll('[data-section-link]').forEach((link) => {",
  "    link.addEventListener('click', (event) => {",
  "      event.preventDefault();",
  "      const section = link.getAttribute('data-section-link') ?? 'overview';",
  "      const projectSlug = state.selectedProject?.slug ?? initialProjectSlug();",
  "      if (!projectSlug) return;",
  "      state.pathname = buildProjectPath(projectSlug, section);",
  "      history.pushState({}, '', state.pathname);",
  "      renderFocusedView();",
  "      renderStatus();",
  "    });",
  "  });",
  "}",
  "function renderSectionNav() {",
  "  if (!els.sectionNav || !els.sectionCopy) return;",
  "  const copy = {",
  "    overview: 'Keep the landing route focused on project context and the next action only.',",
  "    workspace: 'Use the workspace route for file navigation and editing without review panels competing for attention.',",
  "    versions: 'Use the versions route for snapshot review, diff inspection, and restore actions.',",
  "    ai: 'Use the AI route for prompt creation, task inspection, and explicit apply actions.'",
  "  };",
  "  const section = activeSection();",
  "  const projectSlug = state.selectedProject?.slug ?? initialProjectSlug();",
  "  els.sectionCopy.textContent = copy[section] ?? copy.overview;",
  "  if (!projectSlug) {",
  "    els.sectionNav.innerHTML = '<p class=\"panel-note\">Select a project to open a focused route.</p>';",
  "    return;",
  "  }",
  "  const sections = [",
  "    { key: 'overview', label: 'Overview' },",
  "    { key: 'workspace', label: 'Workspace' },",
  "    { key: 'versions', label: 'Versions' },",
  "    { key: 'ai', label: 'AI Tasks' }",
  "  ];",
  "  els.sectionNav.innerHTML = sections.map((item) => `<a href=\"${buildProjectPath(projectSlug, item.key)}\" class=\"route-link${section === item.key ? ' is-active' : ''}\" data-section-link=\"${item.key}\">${item.label}</a>`).join('');",
  "  bindSectionLinks(els.sectionNav);",
  "}",
  "function renderOverview() {",
  "  if (!els.overview) return;",
  "  if (!state.selectedProject) {",
  "    els.overview.innerHTML = '<p>Select a project to view a quieter overview.</p>';",
  "    return;",
  "  }",
  "  const projectTasks = state.tasks.filter((task) => task.projectSlug === state.selectedProject.slug);",
  "  const latestTask = projectTasks[0] ?? null;",
  "  const latestVersion = state.versions[0] ?? null;",
  "  const selectedFile = state.selectedFilePath || 'No file selected';",
  "  els.overview.innerHTML = `<div class=\"panel-head\"><h2>Project Overview</h2></div><p class=\"panel-note\">${escapeHtml(state.selectedProject.description ?? 'No project description yet.')}</p><div class=\"overview-grid\"><article class=\"overview-card\"><strong>Workspace</strong><span>${escapeHtml(selectedFile)}</span><p>Open the focused workspace route when you want to edit files.</p></article><article class=\"overview-card\"><strong>Versions</strong><span>${state.versions.length} snapshots</span><p>${escapeHtml(latestVersion ? latestVersion.message : 'No snapshots yet.')}</p></article><article class=\"overview-card\"><strong>AI Tasks</strong><span>${projectTasks.length} task${projectTasks.length === 1 ? '' : 's'}</span><p>${escapeHtml(latestTask ? `${latestTask.taskSlug} · ${latestTask.status}` : 'No AI task yet.')}</p></article></div><div class=\"route-nav overview-links\"><a href=\"${buildProjectPath(state.selectedProject.slug, 'workspace')}\" class=\"route-link\" data-section-link=\"workspace\">Open Workspace</a><a href=\"${buildProjectPath(state.selectedProject.slug, 'versions')}\" class=\"route-link\" data-section-link=\"versions\">Open Versions</a><a href=\"${buildProjectPath(state.selectedProject.slug, 'ai')}\" class=\"route-link\" data-section-link=\"ai\">Open AI Tasks</a></div>`;",
  "  bindSectionLinks(els.overview);",
  "}",
  "function renderFocusedView() {",
  "  renderSectionNav();",
  "  renderOverview();",
  "  const section = activeSection();",
  "  if (els.overview) els.overview.hidden = section !== 'overview';",
  "  if (els.workspacePanel) els.workspacePanel.hidden = section !== 'workspace';",
  "  if (els.versionsPanel) els.versionsPanel.hidden = section !== 'versions';",
  "  if (els.aiPanel) els.aiPanel.hidden = section !== 'ai';",
  "}"
];
