export const PLATFORM_UI_VERSION_SCRIPT = [
  "function renderVersions() {",
  "  if (!els.versions) return;",
  "  if (!state.selectedProject) {",
  "    els.versions.innerHTML = '<li>No project selected.</li>';",
  "    return;",
  "  }",
  "  if (state.versions.length === 0) {",
  "    els.versions.innerHTML = '<li>No versions yet.</li>';",
  "    return;",
  "  }",
  "  els.versions.innerHTML = state.versions.map((version) => `<li><button type=\"button\" class=\"task-row${state.selectedVersionId === version.versionId ? ' is-active' : ''}\" data-version-id=\"${version.versionId}\"><strong>${escapeHtml(version.message)}</strong><span>${escapeHtml(version.versionId)}</span></button></li>`).join('');",
  "  els.versions.querySelectorAll('[data-version-id]').forEach((button) => {",
  "    button.addEventListener('click', () => {",
  "      const versionId = button.getAttribute('data-version-id') ?? '';",
  "      void selectVersion(versionId);",
  "    });",
  "  });",
  "}",
  "function renderVersionDiff() {",
  "  if (!els.versionDiff) return;",
  "  if (!state.selectedProject) {",
  "    els.versionDiff.innerHTML = '<p>No project selected.</p>';",
  "    return;",
  "  }",
  "  if (!state.selectedVersionId) {",
  "    els.versionDiff.innerHTML = '<p>Select a version to inspect its diff against the current project.</p>';",
  "    return;",
  "  }",
  "  const version = state.versions.find((item) => item.versionId === state.selectedVersionId) ?? null;",
  "  if (!version) {",
  "    els.versionDiff.innerHTML = '<p>Loading version…</p>';",
  "    return;",
  "  }",
  "  if (state.versionDiff === null) {",
  "    els.versionDiff.innerHTML = '<p>Loading diff…</p>';",
  "    return;",
  "  }",
  "  const changes = state.versionDiff.changes.length === 0 ? '<li>No changes against the current project.</li>' : state.versionDiff.changes.map((change) => `<li><code>${change.kind}</code> ${escapeHtml(change.path)}</li>`).join('');",
  "  els.versionDiff.innerHTML = `<h3>${escapeHtml(version.message)}</h3><p>${escapeHtml(version.versionId)}</p><p>Created at ${escapeHtml(version.createdAt)}</p><p>${state.versionDiff.changedFiles} file changes between this snapshot and the current project.</p><ul>${changes}</ul>`;",
  "}",
  "async function refreshProjectVersions() {",
  "  if (!state.selectedProject) return;",
  "  state.versions = [];",
  "  state.selectedVersionId = '';",
  "  state.versionDiff = null;",
  "  renderVersions();",
  "  renderVersionDiff();",
  "  const payload = await requestJson(`/api/projects/${state.selectedProject.slug}/versions`);",
  "  state.versions = payload.versions;",
  "  renderVersions();",
  "  const nextVersionId = state.versions[0]?.versionId ?? '';",
  "  if (nextVersionId) await selectVersion(nextVersionId);",
  "}",
  "async function selectVersion(versionId) {",
  "  if (!state.selectedProject || !versionId) return;",
  "  state.selectedVersionId = versionId;",
  "  state.versionDiff = null;",
  "  renderVersions();",
  "  renderVersionDiff();",
  "  const payload = await requestJson(`/api/projects/${state.selectedProject.slug}/versions/${versionId}/diff`);",
  "  state.versionDiff = payload.diff;",
  "  renderVersionDiff();",
  "  renderStatus();",
  "}",
  "async function handleCreateVersion() {",
  "  if (!state.selectedProject) return;",
  "  const message = (els.versionMessage?.value ?? '').trim();",
  "  if (!message) {",
  "    state.message = 'Snapshot message is required.';",
  "    renderStatus();",
  "    return;",
  "  }",
  "  state.busy = true;",
  "  state.message = `Capturing snapshot for ${state.selectedProject.slug}...`;",
  "  renderStatus();",
  "  try {",
  "    const payload = await requestJson(`/api/projects/${state.selectedProject.slug}/versions`, {",
  "      method: 'POST',",
  "      headers: authHeaders(),",
  "      body: JSON.stringify({ message })",
  "    });",
  "    if (els.versionMessage) els.versionMessage.value = '';",
  "    state.message = `Created project snapshot ${payload.version.versionId}.`;",
  "    await refreshProjectVersions();",
  "    await selectVersion(payload.version.versionId);",
  "  } catch (error) {",
  "    state.message = error instanceof Error ? error.message : 'unknown project version error';",
  "  } finally {",
  "    state.busy = false;",
  "    renderStatus();",
  "  }",
  "}",
  "async function handleRestoreVersion() {",
  "  if (!state.selectedProject || !state.selectedVersionId) return;",
  "  if (!window.confirm(`Restore ${state.selectedVersionId} back into ${state.selectedProject.slug}?`)) return;",
  "  state.busy = true;",
  "  state.message = `Restoring ${state.selectedVersionId} into ${state.selectedProject.slug}...`;",
  "  renderStatus();",
  "  try {",
  "    const payload = await requestJson(`/api/projects/${state.selectedProject.slug}/versions/${state.selectedVersionId}/restore`, {",
  "      method: 'POST',",
  "      headers: authHeaders()",
  "    });",
  "    state.message = `Restored project to ${payload.restoredVersion.versionId}.`;",
  "    await refreshProjectWorkspace();",
  "    await refreshProjectVersions();",
  "    await selectVersion(payload.restoredVersion.versionId);",
  "  } catch (error) {",
  "    state.message = error instanceof Error ? error.message : 'unknown project version error';",
  "  } finally {",
  "    state.busy = false;",
  "    renderStatus();",
  "  }",
  "}"
];
